
package com.mycompany.views.vistas;

import java.awt.Color;

/**
 *
 * @author Julian
 */
public class Index extends javax.swing.JPanel {

    public Index() {
        initComponents();
        InitStyles();
    }

    private void InitStyles(){
        title.putClientProperty("FlatLaf.style","font: bold 24 $h1.light.font");
        title.setForeground(Color.black);
        jLabel2.putClientProperty("FlatLaf.styleClass", "large");
        jLabel2.setForeground(Color.black);
        jLabel3.putClientProperty("FlatLaf.styleClass", "large");
        jLabel3.setForeground(Color.black);
        jLabel4.putClientProperty("FlatLaf.styleClass", "large");
        jLabel4.setForeground(Color.black);
        jLabel5.putClientProperty("FlatLaf.styleClass", "large");
        jLabel5.setForeground(Color.black);
        jLabel6.putClientProperty("FlatLaf.styleClass", "large");
        jLabel6.setForeground(Color.black);
        jLabel7.putClientProperty("FlatLaf.styleClass", "large");
        jLabel7.setForeground(Color.black);
        jLabel8.putClientProperty("FlatLaf.styleClass", "large");
        jLabel8.setForeground(Color.black);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(871, 451));
        setMinimumSize(new java.awt.Dimension(871, 451));
        setPreferredSize(new java.awt.Dimension(871, 451));

        bg.setPreferredSize(new java.awt.Dimension(851, 471));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weight-olympic-bar-vertical-photo-copy-free-space-top-view_147765-335.jpg"))); // NOI18N
        bg.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 0, 445, 459));

        title.setText("Bienvenido");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 860, -1));

        jLabel2.setText("Sistema de Gestión para Control del personal");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 860, -1));

        jLabel3.setText("forma óptima y fácil para mantener el flujo de entrenamientos y usuarios");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, 860, -1));

        jLabel4.setText("Esta herramienta le permitirá llevar un control completo de su Personal,");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 860, -1));

        jLabel5.setText("tendrá acceso a herramientas especiales para tareas específicas, como lo son:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 860, -1));

        jLabel6.setText("• Rutinas (Agregado, Eliminacion, Busqueda, Actualizacion)");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 162, 850, -1));

        jLabel7.setText("• Usuarios (Agregado, Eliminacion, Busqueda, Actualizacion)");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 182, 860, 22));

        jLabel8.setText("• Asistencia (Agregado, Eliminacion, Busqueda, Actualizacion)");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 205, 860, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
